# Generated by Django 4.2.10 on 2025-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkout',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkout',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20),
        ),
    ]
