# Generated by Django 4.2.10 on 2025-05-28 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userworkout_calories_burned_userworkout_intensity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='body_fat',
            field=models.FloatField(blank=True, help_text='Body fat percentage', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='endurance_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='muscle_mass',
            field=models.FloatField(blank=True, help_text='Muscle mass in kgs', null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='strength_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kgs', null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='body_fat_percentage',
        ),
    ]
