# Generated by Django 4.2.10 on 2025-05-29 00:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_progressentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='progressentry',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='strength_score',
            field=models.IntegerField(default=50, help_text='Strength score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='weight',
            field=models.FloatField(default=70.0, help_text='Weight in kgs'),
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.FloatField(default=70.0, help_text='Weight in kgs')),
                ('target_weight', models.FloatField(help_text='Target weight in kgs')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='body_fat',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='endurance_score',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='updated_at',
        ),
    ]
