# Generated by Django 4.2.10 on 2025-06-07 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_remove_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Progress entries'},
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='strength_score',
            field=models.FloatField(help_text='Overall strength score'),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='weight',
            field=models.FloatField(help_text='Weight in kgs'),
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='body_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='muscle_mass',
        ),
    ]
