# Generated by Django 4.2.10 on 2025-05-27 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('intensity', models.PositiveIntegerField(choices=[(1, 'Very Light'), (2, 'Light'), (3, 'Moderate'), (4, 'Somewhat Hard'), (5, 'Hard'), (6, 'Harder'), (7, 'Very Hard'), (8, 'Extremely Hard'), (9, 'Almost Maximum'), (10, 'Maximum')])),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('body_fat', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('muscle_mass', models.FloatField(blank=True, help_text='Muscle mass in kilograms', null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weight histories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Goal'), ('body_fat', 'Body Fat Percentage Goal'), ('muscle_mass', 'Muscle Mass Goal'), ('strength', 'Strength Goal')], max_length=50)),
                ('target_value', models.FloatField()),
                ('start_value', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField()),
                ('achieved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('bench_press', 'Bench Press'), ('squat', 'Squat'), ('deadlift', 'Deadlift'), ('overhead_press', 'Overhead Press'), ('barbell_row', 'Barbell Row')], max_length=50)),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Strength progress',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('fats', models.FloatField(help_text='Fats in grams')),
                ('water', models.FloatField(help_text='Water intake in liters')),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
