# Generated by Django 4.2.10 on 2025-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_exercise_trainingplan_trainingweek_trainingprogress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingday',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AddField(
            model_name='trainingday',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
