# Generated by Django 4.2.10 on 2025-05-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_trainingday_options_trainingday_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='cardio_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='equipment_available',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='excluded_exercises',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='include_deload_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='injuries_limitations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='preferred_exercises',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='training_style',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('supersets', 'Supersets'), ('circuit', 'Circuit Training'), ('pyramid', 'Pyramid Sets'), ('dropsets', 'Drop Sets'), ('german_volume', 'German Volume Training')], default='traditional', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Muscle Growth'), ('endurance', 'Endurance'), ('weight_loss', 'Weight Loss'), ('powerlifting', 'Powerlifting'), ('crossfit', 'CrossFit Style'), ('athletic', 'Athletic Performance'), ('rehabilitation', 'Rehabilitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
