# Generated by Django 4.2.10 on 2025-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_trainingplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermealtime',
            options={'ordering': ['day_of_week', 'order']},
        ),
        migrations.RemoveField(
            model_name='usermealtime',
            name='notes',
        ),
        migrations.AddField(
            model_name='usermealitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='dietary_restrictions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='meals_per_day',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usermealtime',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermealtime',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermealtime',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
