# Generated by Django 4.2.10 on 2025-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermealtime_options_remove_usermealtime_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermealtime',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='usermealitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='meals_per_day',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='usermealtime',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='usermealtime',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='usermealtime',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermealtime',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
