# Generated by Django 4.2.10 on 2025-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usermealtime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermealtime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
