# Generated by Django 4.2.10 on 2025-05-28 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usermealtime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_sleep',
            field=models.FloatField(default=7.0, help_text='Average sleep in hours'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='excluded_foods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exercise_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], default='maintenance', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injuries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_workout_time',
            field=models.CharField(default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stress_level',
            field=models.CharField(default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target weight in kilograms', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_duration',
            field=models.PositiveIntegerField(default=60, help_text='Minutes per workout'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_frequency',
            field=models.PositiveIntegerField(default=3, help_text='Workouts per week'),
        ),
    ]
