# Generated by Django 4.2.10 on 2025-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_activity_level_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='average_sleep',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='excluded_foods',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='exercise_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_workout_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_plan_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_exercises',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress_update_frequency',
            field=models.CharField(default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_timing',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_duration',
            field=models.CharField(choices=[('<5', 'Less than 5 hours'), ('5-6', '5-6 hours'), ('6-7', '6-7 hours'), ('7', '7 hours'), ('7-8', '7-8 hours'), ('8-9', '8-9 hours'), ('9+', 'More than 9 hours')], default='7-8', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (office job, little exercise)'), ('light', 'Lightly active (light exercise 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise 3-5 days/week)'), ('active', 'Very active (hard exercise 6-7 days/week)'), ('very_active', 'Extremely active (physical job, hard exercise daily)')], default='moderate', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='injuries',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stress_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very high')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_duration',
            field=models.CharField(choices=[('15-30', '15-30 minutes'), ('30-45', '30-45 minutes'), ('45-60', '45-60 minutes'), ('60-90', '60-90 minutes'), ('90+', '90+ minutes')], default='45-60', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_frequency',
            field=models.CharField(choices=[('1-2', '1-2 times per week'), ('3-4', '3-4 times per week'), ('4-5', '4-5 times per week'), ('6-7', '6-7 times per week')], default='3-4', max_length=20),
        ),
    ]
