# Generated by Django 4.2.10 on 2025-06-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userprofile_average_sleep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='analytics_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data_sharing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fitness_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marketing_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_plan_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_exercises',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='progress_update_frequency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reminder_timing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sleep_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stress_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_body_fat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workout_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workout_frequency',
        ),
    ]
