# Generated by Django 4.2.10 on 2025-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermealtime',
            name='eaten_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermealtime',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
